receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 'localhost:4317'
      http:
        endpoint: 'localhost:4318'

exporters:
  logging:
    loglevel: debug
  awsxray:
  awsemf:
    log_group_name: 'ADOTLogGroup'
    log_stream_name: 'ADOTLogStream'
    namespace: 'ADOTMetricNS'
    log_retention: 60

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [awsemf, logging]
  telemetry:
    metrics:
      address: localhost:8888
